// ============================================================
// Questions bonus pour l'examen civique
// À uploader dans le même dossier que civisme.html
// ============================================================

// --- Questions de connaissances supplémentaires ---
const QUESTIONS_BONUS = [
  // Principes et valeurs
  { cat: "Principes et valeurs", q: "Quelles sont les couleurs du drapeau français ?",
    options: ["Bleu, blanc, vert", "Bleu, blanc, rouge", "Rouge, blanc, bleu", "Bleu, jaune, rouge"], a: 1,
    exp: "Le drapeau tricolore : bleu, blanc, rouge. Symboles de la Révolution française." },
  { cat: "Principes et valeurs", q: "Quel est le jour de la fête nationale française ?",
    options: ["1er mai", "8 mai", "14 juillet", "11 novembre"], a: 2,
    exp: "Le 14 juillet commémore la prise de la Bastille en 1789 et la Fête de la Fédération en 1790." },
  { cat: "Principes et valeurs", q: "Que célèbre-t-on le 1er mai en France ?",
    options: ["La fête nationale", "La fête du Travail", "L'armistice", "La fête de la République"], a: 1,
    exp: "Le 1er mai est la fête du Travail, jour férié depuis 1947." },
  { cat: "Principes et valeurs", q: "Que célèbre-t-on le 11 novembre ?",
    options: ["L'armistice de 1918 (fin de la Première Guerre mondiale)", "La libération de Paris", "La fin de la Seconde Guerre mondiale", "La fête nationale"], a: 0,
    exp: "Le 11 novembre 1918 marque la fin de la Première Guerre mondiale." },
  { cat: "Principes et valeurs", q: "Quel animal est un symbole de la France ?",
    options: ["L'aigle", "Le coq gaulois", "Le lion", "Le taureau"], a: 1,
    exp: "Le coq gaulois est un symbole national, très utilisé dans le sport." },
  { cat: "Principes et valeurs", q: "Le mariage entre personnes de même sexe est légal en France depuis :",
    options: ["1999", "2004", "2013", "2024"], a: 2,
    exp: "Loi Taubira du 17 mai 2013 (« mariage pour tous »)." },
  { cat: "Principes et valeurs", q: "Le port de la burqa dans l'espace public est :",
    options: ["Autorisé partout", "Interdit (loi de 2010)", "Toléré", "Réservé aux mosquées"], a: 1,
    exp: "Loi du 11 octobre 2010 interdisant la dissimulation du visage dans l'espace public." },
  { cat: "Principes et valeurs", q: "Le PACS est :",
    options: ["Un mariage", "Un Pacte civil de solidarité (union enregistrée)", "Un certificat", "Un contrat de location"], a: 1,
    exp: "Pacte civil de solidarité, créé en 1999, union civile entre deux personnes majeures." },
  { cat: "Principes et valeurs", q: "Quelle déclaration de 1789 énonce les droits fondamentaux ?",
    options: ["Déclaration d'indépendance", "Déclaration des droits de l'homme et du citoyen", "Déclaration universelle des droits de l'homme", "Charte de 1789"], a: 1,
    exp: "Texte fondateur, voté en août 1789." },
  { cat: "Principes et valeurs", q: "L'antisémitisme et le racisme sont :",
    options: ["Des opinions tolérées", "Des délits punis par la loi", "Des critiques politiques", "Des libertés"], a: 1,
    exp: "Ce sont des infractions pénales en France." },

  // Institutions
  { cat: "Institutions", q: "Durée du mandat du président de la République ?",
    options: ["4 ans", "5 ans", "6 ans", "7 ans"], a: 1,
    exp: "Le quinquennat (5 ans), renouvelable une fois, est en vigueur depuis 2002." },
  { cat: "Institutions", q: "Comment est élu le président de la République ?",
    options: ["Par les députés", "Au suffrage universel direct", "Par les sénateurs", "Par le Conseil constitutionnel"], a: 1,
    exp: "Élection au suffrage universel direct depuis 1962." },
  { cat: "Institutions", q: "Quelles sont les deux chambres du Parlement français ?",
    options: ["Assemblée nationale et Sénat", "Chambre des députés et Sénat", "Chambre haute et basse", "Conseil et Assemblée"], a: 0,
    exp: "Le Parlement = Assemblée nationale (députés) + Sénat (sénateurs)." },
  { cat: "Institutions", q: "Combien de sénateurs au Sénat ?",
    options: ["348", "400", "577", "925"], a: 0,
    exp: "Le Sénat compte 348 sénateurs." },
  { cat: "Institutions", q: "Que peut faire le président avec l'Assemblée nationale ?",
    options: ["Rien", "La dissoudre (provoquer de nouvelles élections)", "L'élire", "La supprimer"], a: 1,
    exp: "Article 12 de la Constitution. Le président peut dissoudre l'Assemblée (pas le Sénat)." },
  { cat: "Institutions", q: "Qu'est-ce que le Conseil constitutionnel ?",
    options: ["Un parti politique", "L'institution qui veille au respect de la Constitution", "Le gouvernement", "Une cour de justice"], a: 1,
    exp: "Vérifie la conformité des lois à la Constitution." },
  { cat: "Institutions", q: "Combien d'États composent l'Union européenne actuellement ?",
    options: ["15", "27", "30", "50"], a: 1,
    exp: "27 États membres depuis le Brexit (2020)." },
  { cat: "Institutions", q: "Le drapeau européen porte combien d'étoiles ?",
    options: ["12", "27", "15", "50"], a: 0,
    exp: "12 étoiles (symbole de perfection, indépendant du nombre de pays)." },
  { cat: "Institutions", q: "Qui est le chef des armées en France ?",
    options: ["Le ministre de la Défense", "Le président de la République", "Le Premier ministre", "Le général chef d'état-major"], a: 1,
    exp: "Article 15 de la Constitution." },
  { cat: "Institutions", q: "Combien de départements en France (avec outre-mer) ?",
    options: ["96", "101", "120", "200"], a: 1,
    exp: "101 départements : 96 en métropole + 5 d'outre-mer." },
  { cat: "Institutions", q: "L'hymne de l'Union européenne est :",
    options: ["La Marseillaise", "L'Ode à la joie de Beethoven", "God Save the King", "L'Internationale"], a: 1,
    exp: "L'Ode à la joie, extraite de la 9e symphonie de Beethoven." },

  // Droits et devoirs
  { cat: "Droits et devoirs", q: "Quelle est la différence entre crime et délit ?",
    options: ["Aucune", "Le crime est plus grave (cour d'assises), le délit moins grave (correctionnelle)", "Le délit est plus grave", "C'est pareil"], a: 1,
    exp: "Crime > délit > contravention selon la gravité." },
  { cat: "Droits et devoirs", q: "Qu'est-ce que la présomption d'innocence ?",
    options: ["Tout le monde est coupable", "Toute personne est présumée innocente jusqu'à preuve du contraire", "On présume la culpabilité", "Cela dépend du juge"], a: 1,
    exp: "Principe fondamental : on est innocent tant qu'on n'a pas été condamné définitivement." },
  { cat: "Droits et devoirs", q: "Que fait le Défenseur des droits ?",
    options: ["Il défend l'État", "Il protège les droits des personnes face à l'administration", "Il juge les criminels", "Il vote les lois"], a: 1,
    exp: "Autorité indépendante créée en 2011." },
  { cat: "Droits et devoirs", q: "L'impôt sur le revenu sert à :",
    options: ["Enrichir l'État", "Financer les services publics (école, santé, sécurité)", "Acheter des voitures", "Payer les politiques"], a: 1,
    exp: "Les impôts financent les services publics et la solidarité nationale." },
  { cat: "Droits et devoirs", q: "Le harcèlement moral au travail est :",
    options: ["Toléré", "Un délit puni par la loi", "Normal", "Une pratique managériale"], a: 1,
    exp: "Délit puni de 2 ans d'emprisonnement et 30 000 € d'amende." },
  { cat: "Droits et devoirs", q: "Le code civil français date de :",
    options: ["1789", "1804 (Code Napoléon)", "1958", "2000"], a: 1,
    exp: "Code Napoléon, promulgué en 1804. Il régit le droit privé." },
  { cat: "Droits et devoirs", q: "Que veut dire « état de droit » ?",
    options: ["L'État est au-dessus de tout", "Tout le monde, y compris l'État, est soumis au droit", "L'État fait ce qu'il veut", "Il n'y a pas de loi"], a: 1,
    exp: "Les pouvoirs publics eux-mêmes sont soumis aux lois." },
  { cat: "Droits et devoirs", q: "Pour entrer dans la fonction publique, il faut :",
    options: ["Recommandation d'un élu", "Réussir un concours", "Connaître quelqu'un", "Acheter un poste"], a: 1,
    exp: "Le concours garantit l'égalité d'accès." },
  { cat: "Droits et devoirs", q: "Qu'est-ce que le droit d'asile ?",
    options: ["Le droit de rester chez soi", "Le droit pour une personne persécutée de demander protection", "Le droit de voyager", "Le droit de travailler"], a: 1,
    exp: "Permet à une personne menacée dans son pays d'être protégée par la France." },

  // Histoire et culture
  { cat: "Histoire & culture", q: "Capitale de la France ?",
    options: ["Lyon", "Paris", "Marseille", "Bordeaux"], a: 1,
    exp: "Paris est la capitale et la plus grande ville de France." },
  { cat: "Histoire & culture", q: "Année de la prise de la Bastille ?",
    options: ["1788", "1789", "1791", "1815"], a: 1,
    exp: "14 juillet 1789, événement déclencheur de la Révolution française." },
  { cat: "Histoire & culture", q: "Qui a peint la Joconde ?",
    options: ["Picasso", "Léonard de Vinci", "Monet", "Van Gogh"], a: 1,
    exp: "Léonard de Vinci. La Joconde est exposée au Louvre à Paris." },
  { cat: "Histoire & culture", q: "Auteur des Misérables ?",
    options: ["Émile Zola", "Victor Hugo", "Honoré de Balzac", "Marcel Proust"], a: 1,
    exp: "Victor Hugo, publié en 1862." },
  { cat: "Histoire & culture", q: "Plus haute montagne de France ?",
    options: ["Le Puy de Dôme", "Le Mont Blanc", "Le Pic du Midi", "Le Mont Ventoux"], a: 1,
    exp: "Le Mont Blanc culmine à 4 808 m, dans les Alpes." },
  { cat: "Histoire & culture", q: "Auteur du Petit Prince ?",
    options: ["Antoine de Saint-Exupéry", "Marcel Proust", "Albert Camus", "Jean-Paul Sartre"], a: 0,
    exp: "Saint-Exupéry, publié en 1943. Un des livres les plus traduits au monde." },
  { cat: "Histoire & culture", q: "L'origine de la Tour Eiffel ?",
    options: ["Jeux olympiques", "Exposition universelle de 1889", "Cadeau d'un pays", "Monument religieux"], a: 1,
    exp: "Construite pour l'Exposition universelle de 1889 (centenaire de la Révolution)." },
  { cat: "Histoire & culture", q: "Quel océan borde la France à l'ouest ?",
    options: ["Pacifique", "Indien", "Atlantique", "Arctique"], a: 2,
    exp: "L'océan Atlantique borde la côte ouest." },
  { cat: "Histoire & culture", q: "Quel est le plus long fleuve de France ?",
    options: ["La Seine", "La Loire", "Le Rhône", "La Garonne"], a: 1,
    exp: "La Loire, 1 006 km." },
  { cat: "Histoire & culture", q: "Pierre et Marie Curie ont :",
    options: ["Peint la Joconde", "Découvert la radioactivité (Prix Nobel)", "Écrit Les Misérables", "Été chefs d'État"], a: 1,
    exp: "Marie Curie a obtenu deux prix Nobel (physique 1903, chimie 1911)." },
  { cat: "Histoire & culture", q: "Que représente le Panthéon à Paris ?",
    options: ["Une église active", "Le mausolée des grands hommes et femmes de la République", "Un musée d'art", "Une mairie"], a: 1,
    exp: "Tombeaux des grandes figures (Voltaire, Hugo, Curie, Schoelcher...)." },
  { cat: "Histoire & culture", q: "Le festival de Cannes est consacré à :",
    options: ["La musique", "Le cinéma", "Le théâtre", "La littérature"], a: 1,
    exp: "Festival de cinéma créé en 1946, le plus prestigieux au monde." },
  { cat: "Histoire & culture", q: "Quel président a aboli la peine de mort ?",
    options: ["De Gaulle", "Pompidou", "Mitterrand", "Chirac"], a: 2,
    exp: "François Mitterrand en 1981, sur proposition de Robert Badinter." },

  // Vivre en société
  { cat: "Vivre en société", q: "Numéro du SAMU ?",
    options: ["15", "17", "18", "112"], a: 0,
    exp: "Le 15 est le numéro du SAMU (urgences médicales)." },
  { cat: "Vivre en société", q: "Numéro des pompiers ?",
    options: ["15", "17", "18", "112"], a: 2,
    exp: "Le 18 est le numéro des sapeurs-pompiers." },
  { cat: "Vivre en société", q: "Numéro européen d'urgence ?",
    options: ["15", "17", "18", "112"], a: 3,
    exp: "Le 112 fonctionne dans toute l'UE." },
  { cat: "Vivre en société", q: "Le SMIC est :",
    options: ["Le salaire maximum", "Le salaire minimum légal", "Un impôt", "Une cotisation"], a: 1,
    exp: "Salaire Minimum Interprofessionnel de Croissance, fixé par le gouvernement." },
  { cat: "Vivre en société", q: "Durée légale du travail hebdomadaire en France ?",
    options: ["35 heures", "40 heures", "45 heures", "30 heures"], a: 0,
    exp: "Depuis 2000, la durée légale est de 35 heures par semaine." },
  { cat: "Vivre en société", q: "Que faire en cas de violences conjugales ?",
    options: ["Rester silencieux", "Composer le 3919 (écoute) ou le 17 en urgence", "Régler en famille", "Quitter le pays"], a: 1,
    exp: "3919 : numéro national d'écoute, gratuit, anonyme." },
  { cat: "Vivre en société", q: "Où s'inscrire pour chercher un emploi ?",
    options: ["Au commissariat", "À France Travail (anciennement Pôle emploi)", "À la mairie", "Au tribunal"], a: 1,
    exp: "France Travail accompagne les demandeurs d'emploi depuis janvier 2024." },
  { cat: "Vivre en société", q: "Qu'est-ce que la Sécurité sociale ?",
    options: ["Une assurance privée", "Le système public de protection sociale", "Un parti politique", "Un syndicat"], a: 1,
    exp: "Créée en 1945 : finance santé, familles, retraites, lutte contre la pauvreté." },
  { cat: "Vivre en société", q: "L'école publique est :",
    options: ["Payante", "Gratuite, laïque et obligatoire", "Religieuse", "Réservée aux Français"], a: 1,
    exp: "Lois Jules Ferry (1881-1882) : école gratuite, laïque, obligatoire." },
  { cat: "Vivre en société", q: "Que sont les CAF ?",
    options: ["Cafés publics", "Caisses d'Allocations Familiales", "Tribunaux", "Commissariats"], a: 1,
    exp: "Versent les allocations familiales, l'APL, le RSA, etc." }
];

// --- Mises en situation supplémentaires ---
const MISES_EN_SITUATION_BONUS = [
  { cat: "Mise en situation", q: "Une voisine vient frapper à votre porte la nuit, en pleurs, paniquée. Que faites-vous ?",
    options: ["Vous refermez la porte", "Vous l'accueillez et appelez les secours si nécessaire", "Vous lui dites de rentrer chez elle", "Vous filmez la scène"], a: 1,
    exp: "Devoir d'assistance à personne en danger. L'accueillir et alerter les secours (17, 112, 3919 si violence conjugale)." },
  { cat: "Mise en situation", q: "Votre fils de 16 ans veut arrêter l'école. Que dit la loi ?",
    options: ["Il peut, c'est son choix", "L'instruction est obligatoire jusqu'à 16 ans, et la formation jusqu'à 18 ans", "Il faut l'autorisation du préfet", "Pas de problème jusqu'à 14 ans"], a: 1,
    exp: "Depuis 2020, obligation de formation jusqu'à 18 ans (école, apprentissage, service civique...)." },
  { cat: "Mise en situation", q: "Vous trouvez un téléphone perdu dans le métro. Vous :",
    options: ["Le gardez", "Le déposez aux objets trouvés ou au commissariat", "Le vendez", "Le jetez"], a: 1,
    exp: "Le bon comportement civique est de remettre l'objet trouvé au service compétent." },
  { cat: "Mise en situation", q: "Un policier vous demande votre carte d'identité. Que faites-vous ?",
    options: ["Vous refusez", "Vous présentez votre pièce d'identité poliment", "Vous l'insultez", "Vous fuyez"], a: 1,
    exp: "Le contrôle d'identité est un acte légal de la police. Vous devez prouver votre identité." },
  { cat: "Mise en situation", q: "Au travail, votre patron vous propose de vous payer en partie au noir. Vous :",
    options: ["Acceptez, c'est plus avantageux", "Refusez : c'est illégal et vous serez moins bien protégé (chômage, retraite)", "Acceptez et le dénoncez ensuite", "Acceptez à condition de payer moins d'impôts"], a: 1,
    exp: "Travail dissimulé illégal. Le salarié perd ses droits sociaux (chômage, retraite, congés payés)." },
  { cat: "Mise en situation", q: "Une amie est victime de violences conjugales mais refuse de porter plainte. Comment l'aider ?",
    options: ["La forcer", "L'écouter, lui proposer le 3919 et l'orienter vers une association", "Aller voir son conjoint", "Ne rien faire"], a: 1,
    exp: "3919 : numéro d'écoute. Associations comme la Fédération Solidarité Femmes accompagnent les victimes." },
  { cat: "Mise en situation", q: "Votre enfant veut faire du sport dans son école. C'est :",
    options: ["Réservé aux garçons", "Un droit pour tous, fille ou garçon, sans discrimination", "Payant uniquement", "Interdit"], a: 1,
    exp: "Égalité d'accès au sport, sans distinction de genre. Discrimination interdite." },
  { cat: "Mise en situation", q: "Vous voulez ouvrir un compte en banque en France. Vous devez :",
    options: ["Être français", "Justifier de votre identité et d'un domicile (droit au compte garanti)", "Avoir un emploi", "Payer une caution"], a: 1,
    exp: "Le droit au compte est garanti pour tout résident en France (Banque de France peut désigner une banque)." },
  { cat: "Mise en situation", q: "Un commerçant refuse de vous servir parce que vous êtes étranger. C'est :",
    options: ["Son droit", "Une discrimination illégale, sanctionnée par la loi", "Compréhensible", "Une habitude"], a: 1,
    exp: "Refus de vente discriminatoire : 3 ans de prison et 45 000 € d'amende." },
  { cat: "Mise en situation", q: "Vous voulez créer une association. C'est :",
    options: ["Très compliqué et payant", "Libre et simple (loi 1901), avec déclaration en préfecture", "Réservé aux Français", "Interdit"], a: 1,
    exp: "Loi du 1er juillet 1901 : la liberté d'association est garantie. Déclaration en préfecture." },
  { cat: "Mise en situation", q: "Au travail, on vous demande de fournir un certificat médical de grossesse. C'est :",
    options: ["Normal pour préparer le congé", "Illégal : l'employeur ne peut exiger cette information", "Obligatoire pour les CDI", "Une habitude"], a: 1,
    exp: "L'employeur ne peut pas demander si une candidate est enceinte ni exiger ce type de certificat (discrimination)." },
  { cat: "Mise en situation", q: "Vous êtes témoin d'un accident de la route avec un blessé. Vous devez :",
    options: ["Continuer votre route", "Vous arrêter, sécuriser, alerter les secours (15 ou 112)", "Filmer", "Déplacer le blessé"], a: 1,
    exp: "Non-assistance à personne en danger = délit. Alerter et sécuriser, ne pas déplacer le blessé sauf risque immédiat." },
  { cat: "Mise en situation", q: "Votre voisin sort une arme pendant une dispute de voisinage. Que faites-vous ?",
    options: ["Vous l'affrontez", "Vous vous mettez en sécurité et appelez immédiatement le 17", "Vous criez plus fort", "Vous ne faites rien"], a: 1,
    exp: "Situation de danger immédiat : se protéger et alerter la police (17 ou 112)." },
  { cat: "Mise en situation", q: "Vous achetez un appareil neuf qui tombe en panne au bout d'une semaine. Vous avez droit à :",
    options: ["Rien", "La garantie légale de conformité (2 ans minimum)", "Un échange uniquement", "Un avoir"], a: 1,
    exp: "Garantie légale de conformité de 2 ans pour tout produit neuf : remplacement ou remboursement." },
  { cat: "Mise en situation", q: "Votre propriétaire augmente brutalement votre loyer en cours de bail. C'est :",
    options: ["Son droit", "Encadré par la loi : une augmentation hors révision annuelle est interdite", "Normal", "Acceptable s'il prévient"], a: 1,
    exp: "Le loyer ne peut être révisé qu'une fois par an, selon l'indice IRL, et seulement si le bail le prévoit." }
];

// ============================================================
// INJECTION dans l'app : ajoute les nouvelles questions
// ============================================================
if (typeof QUESTIONS_CONNAISSANCES !== 'undefined') {
  QUESTIONS_CONNAISSANCES.push(...QUESTIONS_BONUS);
}
if (typeof MISES_EN_SITUATION !== 'undefined') {
  MISES_EN_SITUATION.push(...MISES_EN_SITUATION_BONUS);
}
